# Generated by Django 4.2.13 on 2024-10-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
